const cseData = [
  {
    id: 1,
    category: "CSE",
    level: "easy",
    question: "Which data structure uses the LIFO principle?",
    options: ["Queue", "Stack", "Array", "Linked List"],
    answer: "Stack",
  },
  {
    id: 2,
    category: "CSE",
    level: "easy",
    question: "Which keyword is used to define a function in JavaScript?",
    options: ["def", "function", "func", "lambda"],
    answer: "function",
  },
  {
    id: 3,
    category: "CSE",
    level: "easy",
    question: "Which language is primarily used for web development?",
    options: ["Python", "HTML", "C++", "Java"],
    answer: "HTML",
  },
  {
    id: 4,
    category: "CSE",
    level: "easy",
    question: "What is the full form of SQL?",
    options: [
      "Structured Query Language",
      "Simple Query Language",
      "Sequential Query Logic",
      "System Query Logic",
    ],
    answer: "Structured Query Language",
  },
  {
    id: 5,
    category: "CSE",
    level: "easy",
    question: "What does CPU stand for?",
    options: [
      "Central Processing Unit",
      "Central Program Utility",
      "Core Program Unit",
      "Control Processing Unit",
    ],
    answer: "Central Processing Unit",
  },
  {
    id: 6,
    category: "CSE",
    level: "medium",
    question: "Which sorting algorithm has the best average case performance?",
    options: ["Bubble Sort", "Quick Sort", "Selection Sort", "Insertion Sort"],
    answer: "Quick Sort",
  },
  {
    id: 7,
    category: "CSE",
    level: "medium",
    question: "Which data structure is used for recursion?",
    options: ["Queue", "Stack", "Tree", "Array"],
    answer: "Stack",
  },
  {
    id: 8,
    category: "CSE",
    level: "medium",
    question: "Which of the following is not a programming language?",
    options: ["Python", "HTML", "Java", "C#"],
    answer: "HTML",
  },
  {
    id: 9,
    category: "CSE",
    level: "medium",
    question: "Which of these is an example of an operating system?",
    options: ["MS Word", "Windows", "Google Chrome", "Oracle"],
    answer: "Windows",
  },
  {
    id: 10,
    category: "CSE",
    level: "medium",
    question: "Which command is used to initialize a Git repository?",
    options: ["git start", "git init", "git push", "git begin"],
    answer: "git init",
  },
  {
    id: 11,
    category: "CSE",
    level: "medium",
    question: "Which principle does OOP use to hide internal details?",
    options: ["Inheritance", "Polymorphism", "Encapsulation", "Abstraction"],
    answer: "Encapsulation",
  },
  {
    id: 12,
    category: "CSE",
    level: "medium",
    question: "Which protocol is used for transferring web pages?",
    options: ["HTTP", "FTP", "SMTP", "SNMP"],
    answer: "HTTP",
  },
  {
    id: 13,
    category: "CSE",
    level: "medium",
    question: "Which data type is immutable in Python?",
    options: ["List", "Set", "Tuple", "Dictionary"],
    answer: "Tuple",
  },
  {
    id: 14,
    category: "CSE",
    level: "medium",
    question: "Which HTML tag is used for the largest heading?",
    options: ["<head>", "<h1>", "<h6>", "<title>"],
    answer: "<h1>",
  },
  {
    id: 15,
    category: "CSE",
    level: "medium",
    question: "Which part of a computer executes instructions?",
    options: ["Monitor", "Keyboard", "CPU", "Hard Disk"],
    answer: "CPU",
  },
  {
    id: 16,
    category: "CSE",
    level: "medium",
    question: "Which one is not an OOP concept?",
    options: ["Encapsulation", "Abstraction", "Recursion", "Polymorphism"],
    answer: "Recursion",
  },
  {
    id: 17,
    category: "CSE",
    level: "medium",
    question: "Which keyword is used for inheritance in Java?",
    options: ["inherits", "extends", "implements", "uses"],
    answer: "extends",
  },
  {
    id: 18,
    category: "CSE",
    level: "medium",
    question: "What is the default port number for HTTP?",
    options: ["21", "22", "80", "8080"],
    answer: "80",
  },
  {
    id: 19,
    category: "CSE",
    level: "hard",
    question: "What is the time complexity of binary search?",
    options: ["O(n)", "O(n log n)", "O(log n)", "O(1)"],
    answer: "O(log n)",
  },
  {
    id: 20,
    category: "CSE",
    level: "hard",
    question: "Which of the following is a NoSQL database?",
    options: ["MySQL", "MongoDB", "PostgreSQL", "SQLite"],
    answer: "MongoDB",
  },
  {
    id: 21,
    category: "CSE",
    level: "hard",
    question: "Which algorithm is used in Dijkstra’s shortest path?",
    options: [
      "Dynamic Programming",
      "Greedy",
      "Divide and Conquer",
      "Backtracking",
    ],
    answer: "Greedy",
  },
  {
    id: 22,
    category: "CSE",
    level: "hard",
    question: "Which memory is volatile?",
    options: ["ROM", "Cache", "RAM", "Hard Disk"],
    answer: "RAM",
  },
  {
    id: 23,
    category: "CSE",
    level: "hard",
    question: "Which of the following is not a DBMS?",
    options: ["MySQL", "MongoDB", "Linux", "Oracle"],
    answer: "Linux",
  },
  {
    id: 24,
    category: "CSE",
    level: "hard",
    question: "What is the output of 3 + 2 * 2 in Python?",
    options: ["10", "7", "8", "9"],
    answer: "7",
  },
  {
    id: 25,
    category: "CSE",
    level: "hard",
    question: "What is the Big O of linear search?",
    options: ["O(log n)", "O(n)", "O(1)", "O(n^2)"],
    answer: "O(n)",
  },
  {
    id: 26,
    category: "CSE",
    level: "hard",
    question: "Which part of a computer connects CPU with memory?",
    options: ["Bus", "Controller", "Register", "Decoder"],
    answer: "Bus",
  },
  {
    id: 27,
    category: "CSE",
    level: "hard",
    question: "Which type of language is Python?",
    options: ["Low-level", "High-level", "Assembly", "Machine"],
    answer: "High-level",
  },
  {
    id: 28,
    category: "CSE",
    level: "hard",
    question: "Which sorting algorithm is best for large datasets?",
    options: ["Bubble Sort", "Quick Sort", "Insertion Sort", "Selection Sort"],
    answer: "Quick Sort",
  },
  {
    id: 29,
    category: "CSE",
    level: "hard",
    question: "What is the function of DNS?",
    options: [
      "Translates domain names to IP",
      "Stores data",
      "Routes packets",
      "Manages databases",
    ],
    answer: "Translates domain names to IP",
  },
  {
    id: 30,
    category: "CSE",
    level: "hard",
    question: "What does API stand for?",
    options: [
      "Application Programming Interface",
      "Application Process Integration",
      "Applied Programming Input",
      "Application Processing Instance",
    ],
    answer: "Application Programming Interface",
  },
  {
    id: 31,
    category: "CSE",
    level: "hard",
    question: "Which algorithm is used in RSA encryption?",
    options: ["Asymmetric Key", "Symmetric Key", "Hashing", "Diffie-Hellman"],
    answer: "Asymmetric Key",
  },
  {
    id: 32,
    category: "CSE",
    level: "hard",
    question:
      "Which OS scheduling algorithm gives minimum average waiting time?",
    options: ["FCFS", "SJF", "Round Robin", "Priority"],
    answer: "SJF",
  },
  {
    id: 33,
    category: "CSE",
    level: "hard",
    question: "Which protocol secures communication over the internet?",
    options: ["HTTP", "HTTPS", "FTP", "SMTP"],
    answer: "HTTPS",
  },
  {
    id: 34,
    category: "CSE",
    level: "hard",
    question: "Which keyword is used to prevent inheritance in Java?",
    options: ["abstract", "final", "static", "private"],
    answer: "final",
  },
  {
    id: 35,
    category: "CSE",
    level: "hard",
    question: "Which type of machine learning algorithm needs labeled data?",
    options: ["Supervised", "Unsupervised", "Reinforcement", "Deep Learning"],
    answer: "Supervised",
  },
  {
    id: 36,
    category: "CSE",
    level: "hard",
    question: "Which HTTP method is idempotent?",
    options: ["POST", "GET", "PATCH", "CONNECT"],
    answer: "GET",
  },
  {
    id: 37,
    category: "CSE",
    level: "hard",
    question: "What is an example of cloud storage?",
    options: ["AWS S3", "RAM", "SSD", "Cache"],
    answer: "AWS S3",
  },
  {
    id: 38,
    category: "CSE",
    level: "hard",
    question: "Which layer of the OSI model handles encryption?",
    options: ["Session", "Presentation", "Application", "Network"],
    answer: "Presentation",
  },
  {
    id: 39,
    category: "CSE",
    level: "hard",
    question: "Which database keyword retrieves data?",
    options: ["GET", "SELECT", "FETCH", "RETRIEVE"],
    answer: "SELECT",
  },
  {
    id: 40,
    category: "CSE",
    level: "hard",
    question: "Which data structure is used for BFS traversal?",
    options: ["Stack", "Queue", "Tree", "Graph"],
    answer: "Queue",
  },
  {
    id: 41,
    category: "CSE",
    level: "hard",
    question: "What does JSON stand for?",
    options: [
      "JavaScript Object Notation",
      "Java Standard Output Name",
      "JavaScript Open Network",
      "Joint System Object Name",
    ],
    answer: "JavaScript Object Notation",
  },
  {
    id: 42,
    category: "CSE",
    level: "hard",
    question: "Which tool is used for containerization?",
    options: ["Git", "Docker", "Kubernetes", "VMware"],
    answer: "Docker",
  },
  {
    id: 43,
    category: "CSE",
    level: "hard",
    question: "Which AI algorithm mimics brain neurons?",
    options: ["Neural Networks", "Decision Trees", "SVM", "Naive Bayes"],
    answer: "Neural Networks",
  },
  {
    id: 44,
    category: "CSE",
    level: "hard",
    question: "Which data structure supports priority queue operations?",
    options: ["Heap", "Stack", "Queue", "Array"],
    answer: "Heap",
  },
  {
    id: 45,
    category: "CSE",
    level: "hard",
    question: "Which keyword is used for exception handling in Python?",
    options: ["catch", "try", "handle", "except"],
    answer: "try",
  },
  {
    id: 46,
    category: "CSE",
    level: "hard",
    question: "Which architecture is used in neural networks?",
    options: ["Client-server", "Feedforward", "Distributed", "Pipeline"],
    answer: "Feedforward",
  },
  {
    id: 47,
    category: "CSE",
    level: "hard",
    question: "Which command creates a new branch in Git?",
    options: ["git branch", "git new", "git create", "git add"],
    answer: "git branch",
  },
  {
    id: 48,
    category: "CSE",
    level: "hard",
    question: "Which algorithm is used for compression?",
    options: ["Huffman", "Merge", "DFS", "Quick Sort"],
    answer: "Huffman",
  },
  {
    id: 49,
    category: "CSE",
    level: "hard",
    question: "Which SQL clause filters rows?",
    options: ["WHERE", "HAVING", "ORDER BY", "GROUP BY"],
    answer: "WHERE",
  },
  {
    id: 50,
    category: "CSE",
    level: "hard",
    question: "Which process model is used in software development?",
    options: ["Waterfall", "Ocean", "Cloud", "Storm"],
    answer: "Waterfall",
  },
];
export default cseData;
